name: Build and Deploy

on:
  push:
    branches:
      - int
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          API_URL: ${{ secrets.API_URL }}

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy

      - run: npm ci
      - run: npm run lint
