name: Build and Deploy

on:
  push:
    branches:
      - int
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set environment variables globally
        run: |
          echo "process.env.API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy

      - run: npm ci
      - run: npm run lint
